# Sunshine Initialization Script
# Run this to set up Sunshine configuration

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$BinDir = Join-Path $ProjectRoot "binaries\streaming"
$SubmoduleDir = Join-Path $ProjectRoot "submodules\sunshine"
$ConfigDir = "C:\ProgramData\Sunshine"

Write-Host "====================================" -ForegroundColor Cyan
Write-Host "Sunshine Initialization" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Check binary
if (-not (Test-Path "$BinDir\sunshine.exe")) {
    Write-Host "[ERROR] sunshine.exe not found" -ForegroundColor Red
    pause
    exit 1
}

# Create config directory
Write-Host "[SETUP] Creating config directory..." -ForegroundColor Yellow
if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
    Write-Host "  Created: $ConfigDir" -ForegroundColor Green
}

# Create subdirectories
$ConfigSubDirs = @(
    "$ConfigDir\config",
    "$ConfigDir\config\assets",
    "$ConfigDir\config\web"
)
foreach ($dir in $ConfigSubDirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

# Copy sunshine.conf
$SunshineConf = @"
# Sunshine Configuration File
# Generated by R-Link

sunshine_name = R-Link Streaming Server
webui_port = 47990
encoder = auto
min_bitrate = 5000
bitrate = 20000
max_bitrate = 50000
fps = [10, 30, 60, 90, 120]
packet_size = 1392
audio_sink = .*(Default|扬声器).*\)$
pin = 0000
pkey = ./pkey.pem
cert = ./cert.pem
upnp = enabled
firewall = enabled
"@

$SunshineConf | Out-File -FilePath "$ConfigDir\config\sunshine.conf" -Encoding UTF8
Write-Host "  [COPY] sunshine.conf" -ForegroundColor Green

# Copy Windows assets from submodule
if (Test-Path "$SubmoduleDir\src_assets\windows\assets") {
    Write-Host "  [COPY] Windows assets..." -ForegroundColor Green
    Copy-Item -Path "$SubmoduleDir\src_assets\windows\assets\*" -Destination "$ConfigDir\config\assets\" -Recurse -Force
}

# Copy web assets
if (Test-Path "$SubmoduleDir\src_assets\common\assets\web\public") {
    Write-Host "  [COPY] Web assets..." -ForegroundColor Green
    Copy-Item -Path "$SubmoduleDir\src_assets\common\assets\web\public\*" -Destination "$ConfigDir\config\web\" -Recurse -Force
}

Write-Host ""
Write-Host "[SUCCESS] Sunshine initialized!" -ForegroundColor Green
Write-Host ""
Write-Host "Config location: $ConfigDir"
Write-Host "Web UI: http://localhost:47990"
Write-Host ""
Write-Host "You can now run: start.bat"
pause
